presubmits:
  - name: pull-kubestellar-verify
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kubestellar/kubestellar"
    spec:
      containers:
        - image: ghcr.io/kubestellar/infra/build:1.24.2-1
          command:
            - make
            - verify-boilerplate
            - verify-codegen
            - verify-go-versions
            - verify-imports
            - verify-modules
          resources:
            requests:
              memory: 1Gi
              cpu: 1

  - name: pull-kubestellar-lint
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kubestellar/kubestellar"
    spec:
      containers:
        - image: ghcr.io/kubestellar/infra/build:1.24.2-1
          command:
            - make
            - lint
          resources:
            requests:
              memory: 4Gi
              cpu: 2

  - name: pull-kubestellar-test-unit
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kubestellar/kubestellar"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: ghcr.io/kubestellar/infra/build:1.24.2-1
          command:
            - make
            - test
          env:
            - name: USE_GOTESTSUM
              value: "1"
          resources:
            requests:
              memory: 4Gi
              cpu: 2

# Simple Tide configuration to prevent premature merges
tide:
  queries:
    - repos:
        - kubestellar/kubestellar
      labels:
        - lgtm
        - approved
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-rebase

  # Required contexts - block merge until ALL tests pass
  context_options:
    required-contexts:
      # Prow presubmits
      - pull-kubestellar-verify
      - pull-kubestellar-lint
      - pull-kubestellar-test-unit
      # GitHub Actions workflows
      - "Test end to end / Tests in ginkgo"
      - "Test end to end / Test in bash"
      - "Run integration tests / Test"
      - "PR Title Verifier / verify"
