title: KCP-Edge Documentation
navbar-text-col: "#FFFFFF"
avatar: "./contrib/logo/kcp-edge-square_ico32.ico"
theme: minima
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
social-network-links:
  github: kcp-dev/edge-mc
  youtube: kcp-edge
