title: KCP-Edge Documentation
navbar-text-col: "#FFFFFF"
avatar: "./contrib/logo/kcp-edge-square_ico32.ico"
theme: minima
plugins:
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
minima:
  social_links:
    github: "https://github.com/kcp-dev/edge-mc"
    youtube: "https://www.youtube.com/playlist?list=PL1ALKGr_qZKc9jyv1EfOFNfoAJo9Q6Ebd"
