title: KCP-Edge Documentation
author:
  name: Andy Anderson
  email: "andy@clubanderson.com"
navbar-text-col: "#FFFFFF"
avatar: "./contrib/logo/kcp-edge-square_ico32.ico"
theme: just-the-docs
url: https://kcp-edge.github.io
plugins:
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
minima:
  social_links:
    github: kcp-dev/edge-mc
    youtube_channel: PL1ALKGr_qZKc9jyv1EfOFNfoAJo9Q6Ebd
