{{- if index .Values "argo-cd" "install" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-argocd-kubestellar-operator"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Release.Name }}-argocd-kubestellar-operator"
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - tenancy.kflex.kubestellar.org
  resources:
  - controlplanes
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Release.Name }}-argocd-kubestellar-operator"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ .Release.Name }}-argocd-kubestellar-operator"
subjects:
- kind: ServiceAccount
  name: "{{ .Release.Name }}-argocd-kubestellar-operator"
  namespace: {{ .Release.Namespace }}
{{- end }}
