apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-rbac-proxy
  labels:
    app: kube-rbac-proxy
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 5s
    path: /metrics
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - %WDS_NS%
  selector:
    matchLabels:
      app: kube-rbac-proxy
