name: Bug Report
description: Create a report to help us improve
title: "bug: "
labels:
  - kind/bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        Here is how you can help us serve you better:
        
        Lets gather your kubectl and kubeconfig information first:
          - save kubectl output to a file
          - include a reference to what $KUBECONFIG was set to at the time of your kubectl usage
        Lets get KubeStellar specific context now:
          collection of KubeStellar Core user-facing effects:
            - ‘kubectl get synctarget,location -o yaml ’ objects from the inventory space(s)
            - ‘kubectl get edgeplacement,customizer -o yaml’ to show all your  (if any) objects from the workload description space(s)
            - ‘kubectl config get-contexts’ , for each relevant kubeconfig , to show a summary of its contents
            - ‘kubectl version’ for each relevant kubeconfig.
            - ‘kubestellar-version’
            - ‘kubestellar-release’

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Please provide a clear and concise description of the bug.
      placeholder: |
        Add logs and screenshots if any.
    validations:
      required: true

  - type: textarea
    id: reproducing
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See the error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
