name: SIG KCP-Edge Community Meeting Agenda
description: Create a new weekly meeting agenda
title: "SIG KCP-Edge Community Meeting [DATE]"
labels:
  - community-meeting
body:
  - type: textarea
    attributes:
      label: Overview
      value: |
        At 10am Eastern, 7am Pacific, 2pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T140000&p1=1440&p2=4826&p3=234&p4=195)

        Video call link: [https://ibm.webex.com/ibm/j.php?MTID=mc9015c89e56fb75fc0956a1bdb93f931](https://www.google.com/url?q=https://ibm.webex.com/ibm/j.php?MTID%3Dmc9015c89e56fb75fc0956a1bdb93f931&sa=D&source=calendar&ust=1667748105933449&usg=AOvVaw1Wsf7HrBZqYzOOC06nnJCD)
        Or dial: ‪1-844-531-0958‬ PIN: ‪145 377 9958‬#
        More phone numbers: https://ibm.webex.com/webappng/sites/ibm/meeting/scheduler
        Or join via SIP: sip:1453779958@ibm.webex.com

        Meeting recordings available on YouTube at https://www.youtube.com/playlist?list=PLqN7RcoCwL96nXIIW6O51l8Lu_J-f5D27

        Add topics you'd like to discuss below!
    validations:
      required: true
