{{- range $cp := (concat (.Values.ITSes | default list) (.Values.WDSes | default list) ) }}
{{- if eq $cp.type "host" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeflex-manager-cluster-admin-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubeflex-controller-manager
  namespace: kubeflex-system
{{- break }}
{{- end }}
{{- end }}