apiVersion: control.kubestellar.io/v1alpha1
kind: BindingPolicy
metadata:
  name: bindingpolicy1
spec:
  clusterSelectors:
  - matchLabels: {"location-group":"edge"}
  downsync:
  - objectSelectors:
    - matchLabels: {"argocd.argoproj.io/instance":"guestbook"}

