apiVersion: edge.kubestellar.io/v2alpha1
kind: EdgePlacement
metadata:
  name: dev
spec:
  locationSelectors:
  - matchLabels:
      env: dev
  downsync:
  - apiGroup: ""
    resources: [ configmaps ]
    namespaces: [ dev-namespace ]
    objectNames: [ "*" ]
