---
apiVersion: edge.kubestellar.io/v2alpha1
kind: Location
metadata:
  name: prod
  labels:
    env: prod
spec:
  instanceSelector:
    matchLabels:
      env: prod
  resource:
    group: edge.kubestellar.io
    resource: synctargets
    version: v2alpha1
