---
apiVersion: scheduling.kcp.io/v1alpha1
kind: Placement
metadata:
  name: dev
spec:
  locationResource:
    group: workload.kcp.io
    resource: synctargets
    version: v1alpha1
  locationSelectors:
  - matchLabels:
      env: prod
  locationWorkspace: root:compute
  namespaceSelector:
    matchLabels:
      env: dev
