apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: edge.kcp.io
spec:
  latestResourceSchemas:
  - v230126-0a8bf97.edgeplacements.edge.kcp.io
  - v230221-fa5dc39.singleplacementslices.edge.kcp.io
status: {}
