apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: edge.kcp.io
spec:
  latestResourceSchemas:
  - v230228-0f548e5.singleplacementslices.edge.kcp.io
  - v230228-7fe2c02.edgeplacements.edge.kcp.io
status: {}
