apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: storage.k8s.io
spec:
  latestResourceSchemas:
  - v230615-d48020c8.csistoragecapacities.storage.k8s.io
status: {}
