apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: autoscaling
spec:
  latestResourceSchemas:
  - v230615-d48020c8.horizontalpodautoscalers.autoscaling
status: {}
