{{- if .Values.InstallPCHs }}
apiVersion: tenancy.kflex.kubestellar.org/v1alpha1
kind: PostCreateHook
metadata:
  name: its
  labels:
    kflex.kubestellar.io/cptype: its
spec:
  templates:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: "{{"{{.HookName}}"}}"
    spec:
      template:
        spec:
          containers:
          - name: "{{"{{.HookName}}-clusteradm"}}"
            image: quay.io/kubestellar/clusteradm:{{.Values.CLUSTERADM_VERSION}}
            args:
            - init
            - -v={{.Values.verbosity.clusteradm | default .Values.verbosity.default | default 2 }}
            env:
            - name: KUBECONFIG
              value: "{{"/etc/kube/{{.ITSkubeconfig}}"}}"
            volumeMounts:
            - name: kubeconfig
              mountPath: "/etc/kube"
              readOnly: true
          - name: "{{"{{.HookName}}-statusaddon"}}"
            image: quay.io/kubestellar/helm:{{.Values.HELM_VERSION}}
            args:
            - upgrade
            - --install
            - status-addon
            - oci://ghcr.io/kubestellar/ocm-status-addon-chart
            - --version
            - v{{.Values.OCM_STATUS_ADDON_VERSION}}
            - --namespace
            - open-cluster-management
            - --create-namespace
            - --set
            - "verbosity.controller={{.Values.verbosity.status_controller | default .Values.verbosity.default | default 2 }}"
            - --set
            - "verbosity.agent={{.Values.verbosity.status_agent | default .Values.verbosity.default | default 2 }}"
            env:
            - name: HELM_CONFIG_HOME
              value: "/tmp"
            - name: HELM_CACHE_HOME
              value: "/tmp"
            - name: KUBECONFIG
              value: "{{"/etc/kube/{{.ITSkubeconfig}}"}}"
            volumeMounts:
            - name: kubeconfig
              mountPath: "/etc/kube"
              readOnly: true
          volumes:
          - name: kubeconfig
            secret:
              secretName: "{{"{{.ITSSecretName}}"}}"
          restartPolicy: Never
      backoffLimit: 1
{{- end }}
