name: Add issues to project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issues to project
    runs-on: ubuntu-latest
    environment: projects
    steps:
      - name: add to project
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/kcp-dev/projects/12
          github-token: ${{ secrets.GHPROJECT_TOKEN_REPO }}
      
      - name: Move to In Progress
        uses: kin/gh-action-move-issue-to-column@1.0
        with:
          access-token: "#{{ secrets.GHPROJECT_TOKEN_REPO }}"
          project-name: "KubeStellar"
          target-column: "Todo"
