name: Generate and push docs
run-name: Generate and push docs - ${{ github.ref_name }}

on:
  # So we can trigger manually if needed
  workflow_dispatch:
    inputs:
      aliasLatest:
        description: 'Alias to latest'
        required: false
        default: ''
        type: choice
        options:
        - ''
        - '--alias-to=latest'
      aliasStable:
        description: 'Alias to stable'
        required: false
        default: ''
        type: choice
        options:
        - ''
        - '--alias-to=stable'
  # To confirm any changes to docs build successfully, without deploying them
  push:
    branches:
      - main
      - "release-*"
    paths:
      - "docs/**"
      - "*.md"
      - ".github/workflows/docs-gen-and-push.yaml"

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}

jobs:
  generate-and-push:
    if: github.repository_owner == 'kubestellar'
    name: Generate and push docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.GH_ALL_PROJECT_TOKEN }}
          persist-credentials: 'true'
  
      - run: git fetch origin gh-pages

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: make deploy-docs
        env:
          ALIAS_LATEST: ${{ github.event.inputs.aliasLatest }}
          ALIAS_STABLE: ${{ github.event.inputs.aliasStable }}
        run: make deploy-docs DEPLOY_DOCS_EXTRA="$ALIAS_LATEST $ALIAS_STABLE"
