name: Elapsed Time Collector

on:
  # So we can trigger manually if needed
  workflow_dispatch:
  # To confirm any changes to docs build successfully, without deploying them
  workflow_run:
    workflows: [""]
    types:
      - completed

permissions:
  contents: write

jobs:
  broken-links-crawler:
    name: broken-links-crawler
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: get time diff in minutes
        shell: bash
        run: echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

          
