name: new Add Issues to Project

on:
  issues:
    types: [opened]
env:
  GITHUB_API_TOKEN: ${{ secrets.NEW_ISSUE_ACTION_PAT }}

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
    - name: Assign new issues to the project
      uses: technote-space/create-project-card-action@v1
      with:
        PROJECT: Backlog
        COLUMN: Todo
        CHECK_ORG_PROJECT: true
