name: Move issue once milestoned

on:
  issues:
    types: [milestoned]
jobs:
  Move_Milestoned_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.GHPROJECT_TOKEN }}"
        project-url: "https://github.com/orgs/kcp-dev/projects/12"
        column-name: "Todo"
        milestone-name: "2023q3 PoC"
#         columns-to-ignore: "In Review,Ready to deploy,Done"
