name: Run Doc Shells - QS

on:
  # So we can trigger manually if needed
  workflow_dispatch:
  # To confirm any changes to docs build successfully, without deploying them
  pull_request:
    branches:
      - main
#       - "release-*"
    paths:
      - "docs/content/Getting-Started/quickstart.md"
      - "docs/content/Getting-Started/quickstart-subs/**"
      - ".github/workflows/run-doc-shells.yml"
  push:
    branches:
      - main
#       - "release-*"
    paths:
      - "docs/content/Getting-Started/quickstart.md"
      - "docs/content/Getting-Started/quickstart-subs/**"
      - ".github/workflows/run-doc-shells.yml"

permissions:
  contents: write

# concurrency:
#   group: ${{ github.workflow }}

jobs:
  run-doc-shells:
    name: Run doc shells - for QS e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: git fetch origin main

      - uses: actions/setup-go@v4
        with:
          go-version: v1.19
          cache: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"

      - name: Install jq
        uses: dcarbone/install-jq-action@v1.0.1

      - name: Install yq
        uses: frenck/action-setup-yq@v1

      - name: Install docker
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
        
      - run: |
          set -x
          docker version

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        id: install
  

      - run: |
          make MANIFEST="'content/Getting-Started/quickstart-subs/quickstart-1-install-and-run-kubestellar.md',\
            'content/Getting-Started/quickstart-subs/quickstart-2-apache-example-deployment-a-kind-clusters-florin.md',\
            'content/Getting-Started/quickstart-subs/quickstart-2-apache-example-deployment-a-kind-clusters-guilder.md',\
            'content/Getting-Started/quickstart-subs/quickstart-2-apache-example-deployment-b-create-imw-and-wmw.md',\
            'content/Getting-Started/quickstart-subs/quickstart-2-apache-example-deployment-c-onboarding-clusters.md',\
            'content/Getting-Started/quickstart-subs/quickstart-2-apache-example-deployment-d-create-and-deploy-apache-into-clusters.md',\
            'content/Getting-Started/quickstart-subs/quickstart-3-teardown-the-environment.md'" \
            run-doc-shells
      
