name: Spellcheck Action
run-name: Spellcheck Action - ${{ github.ref_name }}

on:
  # So we can trigger manually if needed
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 5"
  # To confirm any changes to docs build successfully, without deploying them
#   pull_request:
#     branches:
#       - main
#       - "release-*"
#     paths:
# #       - "cmd/**"
#       - "docs/**"
# #       - "pkg/**"
#       - ".github/workflows/spellcheck_action.yaml"
  push:
    branches:
      - main
      - "release-*"
    paths:
      - ".github/workflows/spellcheck_action.yml"
      - ".github/spellcheck/.spellcheck.yml"
      - ".github/spellcheck/.wordlist.yml"
#      - "docs/**"
# #       - "cmd/**"
# #       - "pkg/**"

jobs:
  build:
    if: github.repository_owner == 'kubestellar'
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3

    - uses: rojopolis/spellcheck-github-actions@0.33.0
      name: Spellcheck
      with:
        task_name: Markdown
        config_path: .github/spellcheck/.spellcheck.yml
        output_file: spellcheck-output.txt
#         source_files: "docs/content/*"
        
    - uses: actions/upload-artifact@v3
      with:
        name: Spellcheck Output
        path: spellcheck-output.txt
