apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: scheduling.k8s.io
spec:
  latestResourceSchemas:
  - v230615-d48020c8.priorityclasses.scheduling.k8s.io
status: {}
